### ISSUE TITLE
Feature Request: enable access to relationship bendpoints on visual objects

### ISSUE THREAD

**Issue by timhale7** [archimatetool/archi-scripting-plugin#42]
Feature request - enable access to relationship bendpoints on visual objects.

use case: I have a set of relationships - typically serving/served-by - where I'd like to swap the sourceEnd and targetEnd.  That's easy enough to do, 

however...

I've also manually routed the relationship on one or more views.  Using the script doesn't touch the bendpoints, so the original relationship that traversed sourceEnd->bend1->bend2->targetEnd, now begins at the former targetEnd, but still traverses bend1->bend2 on its way to the former sourceEnd.  This kinks the relationship visualization in unexpected and unwelcome ways.

I'd like to be able to reset the sequence of bendpoints so that the relationship's visual representation is preserved.

**Comment by timhale7** [comment]
here's an example.
I have 2 application component objects with a triggering relationship between them.  The relationship has 2 bendpoints.

Exporting the model to an Open Exchange File, I see:
<bendpoint x="373" y="294" />
 <bendpoint x="574" y="305" />

Swapping the sourceEnd and targetEnd, and exporting again, I see:
<bendpoint x="456" y="336" />
<bendpoint x="492" y="264" />

**Comment by Phillipus** [comment]
It's easy enough to implement getBendpoints() (see the new branch I just committed, "bendpoints"), but setting them is a bit more complex. A user would need to delete, move and add bendpoints. The underlying logic of positioning bendpoints is also a bit complicated.

Will have to come back to this one.

**Comment by Phillipus** [comment]
@jbsarrodie I've created a branch "bendpoints" with a basic implementations of getBendpoints() and addBendpoint() methods.

However, I never really did understand the bendpoint positioning logic, and what the index value is for when positioning. We can put this on the "to do" list for now, but just flagged it up in case you could advise at some point (in your very busy schedule!)

**Comment by timhale7** [comment]
I anticipated that it would be a case of reordering the bendpoints in
reverse sequence - on every view where the relationship appears.  Is it
more involved than that?

**Comment by Phillipus** [comment]
> Is it more involved than that?

I think so. The positions of each bendpoint and their order is a bit convoluted. We'll investigate. I've made a start.

**Comment by timhale7** [comment]
thank you! I appreciate it.
Tim

**Comment by Phillipus** [comment]
@timhale7 I came up with a provisional API if you want to test it.

Edit: needs more work

**Comment by Phillipus** [comment]
Some example JS:

```js
// New bendpoint 1
var bp1 = {
    startX: 200,
    startY: 200,
    endX: 10,
    endY: 10
}

// New bendpoint 2
var bp2 = {
    startX: 100,
    startY: 100,
    endX: 20,
    endY: 30
}

// Select the first connection in an opened View
var connection = selection.filter("relationship").first();

// Add bendpoints at index positions
// Can also do:
// connection.addBendpoint(bp1);
// connection.addBendpoint(bp2);
connection.addBendpoint(bp1, 0);
connection.addBendpoint(bp2, 1);

// Get bendpoints
var bendpoints = connection.getBendpoints();

// Log each one so you know the format
bendpoints.forEach(function(bp) {
    console.log(bp);
});

// Delete all bendboints
connection.deleteAllBendpoints();

// Or delete each one by its index
// Indexes will come from the returned list of getBendpoints()

for (var index = bendpoints.length - 1; index >= 0; index--) {
    connection.deleteBendpoint(index);    
}

```

**Comment by Phillipus** [comment]
To figure out how the co-ordinate system works you can open an *.archimate file in a text editor and study these entries:

```xml
<bendpoint startX="126" startY="75" endX="-216" endY="75"/>
<bendpoint startX="198" startY="63" endX="-144" endY="63"/>
<bendpoint startX="246" startY="123" endX="-96" endY="123"/>
```

**Comment by Phillipus** [comment]
I think each pair of co-ords is relative to the connection's start and end points, but I'm not sure why it's done this way. It was implemented this way from the only extant example of implementing bendpoints in Eclipse GEF that I could find many years ago...

**Comment by jbsarrodie** [comment]
Hi,

I'll document the positionning logic of bendpoints later tonight.

@phillipus in fact we shoul expose benpoints using absolute coordinate and store them back as GEF expects them. To my knowledge, this is what we've done for the model exchange file format.

**Comment by Phillipus** [comment]
@jbsarrodie OK, thanks.

The co-ordinates in the *.archimate file match those in the new API. I just thought it better to use those? Not sure now...

**Comment by timhale7** [comment]
much appreciated!  I've downloaded & installed it.  working with it now.

**Comment by jbsarrodie** [comment]
>The co-ordinates in the *.archimate file match those in the new API

Not sure to understand what you mean by "new API".

From previous (early 2015) discussions, bendpoints absolute location calculation is described [here](https://github.com/archimatetool/OpenGroupXMLExchange/blob/master/org.opengroup.archimate.xmlexchange/src/org/opengroup/archimate/xmlexchange/XMLExchangeUtils.java#L99).

The issue is that there is no real coordinate system for bendpoint, but some very specific relative and "elastic" positioning: relative to source and target elements of the relationship, but "elastic" because if you move source or target, then the bendpoint is move/stretched and stays at the same relative position. Hard to explain, but easy to visualize if you test in Archi.

>Not sure now...

I think that exposing startX, startY, endX, endY to jArchi is not a good option because users will have to do the calculation. I find it better to simply provide actual coordinate of the bendpoint itself and convert it back when they changed.

**Comment by Phillipus** [comment]
> Not sure to understand what you mean by "new API".

The new code added in the "bendpoints" branch. ;-)

>  I find it better to simply provide actual coordinate of the bendpoint itself and convert it back when they changed.

OK, no problem.

**Comment by Phillipus** [comment]
> I find it better to simply provide actual coordinate of the bendpoint itself and convert it back when they changed.

Just looked at the code to do this in `XMLExchangeUtils` and it also needs a good chunk of code to convert back again. That's a lot of conversion code! If we use this, we'll probably need to push that code up into the main Archi code so it can be re-used.

Edit - also some code in `XMLModelImporter#addBendpoints()`

**Comment by Phillipus** [comment]
Also, that bendpoint conversion code doesn't work for connection -> connection.

**Comment by jbsarrodie** [comment]
I forgot to illustrate why I think using real/absolute coordinate is important. For @timhale7's use case, it'important to recreate bendpoints at the same place. With absolute coordinate this becomes easy because you just have to get the benpoints' list of the original relationship and set it to the new one in reverse order. No need to do custom calculations.

Btw, this will also allow to use output of layout libraries more easily.

**Comment by Phillipus** [comment]
OK. These are the issues:

- Code from `XMLExchangeUtils` and `XMLModelImporter#addBendpoints()` has to be re-used. Perhaps pushed up to Archi main code for re-use
- The conversion code relies on getting the bounds of the source and target of the connection.
- If the source or target of the connection is another connection then it currently doesn't work (see comment [here](https://github.com/archimatetool/OpenGroupXMLExchange/blob/master/org.opengroup.archimate.xmlexchange/src/org/opengroup/archimate/xmlexchange/XMLExchangeUtils.java) )

**Comment by jbsarrodie** [comment]
>Perhaps pushed up to Archi main code for re-use

I wonder if there is some builtin GEF/draw2d method for that.

>If the source or target of the connection is another connection then it currently doesn't work

I show the comment yesterday. I will have a look. Maybe it's also time for me to define a better behavior for bendpoint when source or target are moved...

**Comment by timhale7** [comment]
So far I'm working towards unstringing and restringing each bendpoint so I can swap the start's and end's.  and then removing the bendpoints and adding them back in reverse sequence.  Somewhere in there I'll swap the relationship source and target.

Absolute coordinates would make this easier, but no big deal, I've already completed swapping start and end.

I've not even tried to tackle a connection-connection relationship.  I've not had one.

**Comment by Phillipus** [comment]
> I wonder if there is some builtin GEF/draw2d method for that.

We can't use GEF/Draw2D to calculate this. The exchange format and jArchi only know about the model ecore elements and their sizes and positions. Same with using the .xml/.archimate files standalone.

**Comment by timhale7** [comment]
I have working code now.  Am swapping source and target on the selected relationship, and modifying/reordering bendpoints on each view's connections.

generally seems to be working, but have encountered odd behavior in an edge case.
files attached, but i can't upload the example archimate file.
- model contains only 2 objects and 1 relationship:  Fred, Wilma, triggering-relationship
- view contains 2 instances of each, with a single triggering-relationship on each pair.
after swapping the triggering relationship's source and target, the 2 relationships have been moved to one instance of the Fred/Wilma pair.

the screenprints I've attached were taken after using my bendpoint code.
the problem is reproducible with the small script I've attached that doesn't change any bendpoints.

could you take a look?

![after 2nd source-target swap](https://user-images.githubusercontent.com/40830379/53206735-54f44680-35f7-11e9-89b5-15f452c84e07.PNG)
![after source-target swap](https://user-images.githubusercontent.com/40830379/53206736-54f44680-35f7-11e9-9f46-9f060567bd8c.PNG)
![before source-target swap](https://user-images.githubusercontent.com/40830379/53206737-54f44680-35f7-11e9-941f-175a30394b7d.PNG)

[testingswapbug.ajs.txt](https://github.com/archimatetool/archi-scripting-plugin/files/2891589/testingswapbug.ajs.txt)

**Comment by Phillipus** [comment]
The code for setting source or target on a relationship checks each View that has the relationship as  a connection. However, it only re-connects to the first instance of the source or target that it finds in the View. This is because it doesn't know which instance to reconnect to if there is more than one. Not sure if that can be overcome, or not.

**Comment by timhale7** [comment]
I think this is an extreme edge case.  I just happened to stumble on it.
Unless you think differently, probably not worth working on.

**Comment by Phillipus** [comment]
Would it be possible for you to:

1. Iterate through all diagram connection instances and store the source/target objects and bendpoints in JS.
2. Delete the connections.
3. Reverse the model relationship.
4. Re-add new connections (with relationship backing) and bendpoints (in reverse) from the info in the stored list

**Comment by timhale7** [comment]
yes.  my suspicions were growing that this might be the solution pattern.

**Comment by timhale7** [comment]
I believe this is going to do the trick.  I have a bit of code cleanup to
do, but it is handling my edge case.

**Comment by timhale7** [comment]
I think I've got it working now. Need to tidy up, and add some safety checks.

**Comment by timhale7** [comment]
Phillipus, I'm having a problem executing isAllowedRelationship().  

I even pasted the example code in my script:
var isAllowed = isAllowedRelationship("assignment-relationship", "business-actor", "business-role");

and get this script error:
Script Error at: javax.script.ScriptException, javax.script.ScriptException: ReferenceError: "isAllowedRelationship" is not defined in file:....

any insight?

**Comment by Phillipus** [comment]
@timhale7 You have to call that on the `$.model` object like this:

`var isAllowed= $.model.isAllowedRelationship("assignment-relationship", "business-actor", "business-role");`

**Comment by timhale7** [comment]
another question - given that the selection is a connection, how do you select the connection's base relationship?  After repeated attempts, I'm just not able to find the method.

**Comment by Phillipus** [comment]
@timhale7 

It's `connection.concept`.

For example:

`var concept = selection.first().concept;`

Where concept could be the base relationship or element depending on type.

(It's probably best to ask general jArchi questions on the Archi Forum as you're likely to get more eyes on the problem there and we can keep this issue focused on implementing Bendpoints. ;-) )

**Comment by timhale7** [comment]
@Phillipus, are you ready to include this feature in the next release?  it all seems to be working for me.

**Comment by Phillipus** [comment]
@timhale7 @jbsarrodie  We can choose:

1. Use the system as it was implemented in the branch (relative co-ords)
2. Devise a system similar to the exchange format (absolute co-ord)

Downsides to (2) are it doesn't work if a connection connects to another connection, and the conversion back and forth is complex.

Or:

3. Implement option (1) and name the API functions so they are clear, like getRelativeBendpoints(), addRelativeBendpoint(). Revisit option (2) and, if implemented, add a new API getAbsoluteBendpoints() and addAbsoluteBendpoints.

**Comment by timhale7** [comment]
in the spirit of good-enough-for-now, I vote for #1, but that's just my (selfish) use-case.  All I was trying to do was reverse the direction of the relationship.  I had no interest in changing any bendpoint values, so all I had to do was reorder the values that were already there.

just thinking out loud, if I were interested in programatically manipulating them, it doesn't strike me as particularly hard to adapt to either one, as long as I can understand how they work.

so, go with what you have until a new use case is presented?  To future proof, you might go ahead and name the existing functions precisely (...relative...), but defer creating any new functions (...absolute...) until a usecase is requested for them

**Comment by jbsarrodie** [comment]
I vote for option 3 (_Implement option (1) and name the API functions so they are clear, like getRelativeBendpoints(), addRelativeBendpoint()_) as it doesn't requires any new development and provide a clear enough API for users.

**Comment by Phillipus** [comment]
OK. I'll review this for the next release. I'm happy with (3).

**Comment by Phillipus** [comment]
All that I would ask from @timhale7 is if you could, from your experience, write a summary documentation of how the relative system works for end users?

**Comment by timhale7** [comment]
I'm happy to contribute what I know - but not sure its to the level of detail you are asking.  I did not have to learn any intricacies of the coordinate system.  All I had to learn was how to manipulate the endpoint data structures that were already on the relationships.  I plan on posting my script once the feature is available.  Where would you like me to post my summary docs so you can review and provide feedback?

**Comment by Phillipus** [comment]
Here would be fine, in this issue. Thanks.

**Comment by timhale7** [comment]
Hi Phil, I seem to be having trouble executing my jarchi script after upgrading to 4.4, even though I replaced the com.archimatetool.script.... file with the one you sent me earlier.  It reports that getBendpoints  is not a function.  

I'd like to add some examples into my documentation, but until I can do that, here's what I've documented.  Feel free to correct/adapt as you see fit.

Bendpoint Manipulation Concepts
1.	Object Concepts:
a.	Relationship objects exist in the model tree
b.	Connection objects exist on a View, and instantiate a Relationship
c.	Bendpoints exist on a Connection on a View

2.	When a Bendpoint is placed on a Connection, it is stored on the Connection as an ordered pair of X and Y coordinates, e.g.:
a.	<insert example here: startX, endX, startY, endY>

3.	Bendpoint X/Y coordinates are stored relative to the originating object, not as absolute X/Y canvas coordinates.

4.	When a Connection has multiple Bendpoints, they are stored in sequence from the originating object to the destination object.

5.	Bendpoints can be programmatically added/modified/deleted with the jArchi plug-in.

6.	Users may wish to use the jArchi plug-in to reverse a Connection direction.  X/Y coordinates on a Connection do not have to be recalculated, they just need to be manipulated as follows:
a.	For each bendpoint, swap the startX/startY value-pair with the endX/endY value-pair.  E.g., {endY: 69, endX: 36, startY: -15, startX: -132} becomes {endY: -15, endX: -132, startY: 69, startX: 36
b.	If multiple bendpoints exist, reverse the order so that bendpoints ordered bp1, bp2, bp3 are removed, modified as above, and reinserted in sequence bp3, bp2, bp1.
c.	In coding, the programmer will need to retrieve the current bendpoints, delete the Connection from the View, swap the Relationship Source and Target, recreate the Connection on the View, and add the modified bendpoints in the reverse sequence to the new Connection.  
i.	N.B., ensure the validity of the new Connection direction before taking action.
ii.	N.B., when you modify the Relationship, you are affecting all related Connections that exist on all Views in the model.  So the full module logic must retrieve the Bendpoints from all Connections on all Views for the Relationship, delete all of those Connections, swap the Relationship Source and Target, reinsert all of the Connections on all of the Views and reestablish each of the Bendpoints on each Connection.

**Comment by Phillipus** [comment]
> Hi Phil, I seem to be having trouble executing my jarchi script after upgrading to 4.4, even though I replaced the com.archimatetool.script.... file with the one you sent me earlier. It reports that getBendpoints is not a function.

Don't know why this is so. I'll generate another one tomorrow.

**Comment by Phillipus** [comment]
Unzip the jar and manually copy to the "plugins" folder.

[com.archimatetool.script_0.4.4.201904032221.zip](https://github.com/archimatetool/archi-scripting-plugin/files/3040807/com.archimatetool.script_0.4.4.201904032221.zip)

**Comment by Phillipus** [comment]
Actually, I think what we need for the documentation is how the x,y relative co-ord system works. i.e how one bendpoint x,y relates to the others or the source/target. 

BTW - because I have other work to do, this won't be released immediately. Perhaps in a couple of weeks or so.

**Comment by Phillipus** [comment]
Proposed Java API on Connection:

```java
public List<Map<String, Integer>> getRelativeBendpoints();

public DiagramModelConnectionProxy addRelativeBendpoint(Map<?, ?> map, int index);

public DiagramModelConnectionProxy deleteAllBendpoints();

public DiagramModelConnectionProxy deleteBendpoint(int index);
```

**Comment by Phillipus** [comment]
Example JS:

```js
// New bendpoint 1
var bp1 = {
    startX: 200,
    startY: 200,
    endX: 10,
    endY: 10
}

// New bendpoint 2
var bp2 = {
    startX: 100,
    startY: 100,
    endX: 20,
    endY: 30
}

// Select the first connection in an opened View
var connection = selection.filter("relationship").first();

// Add bendpoints at index positions
connection.addRelativeBendpoint(bp1, 0);
connection.addRelativeBendpoint(bp2, 1);

// Get bendpoints
var bendpoints = connection.getRelativeBendpoints();
// Or this way
//var bendpoints = connection.relativeBendpoints;

// Log each one so you know the format
bendpoints.forEach(function(bp) {
    console.log(bp);
});

// Delete all bendboints in one go
//connection.deleteAllBendpoints();

// Or delete each one by its index
// Indexes will come from the returned list of getRelativeBendpoints()
for (var index = bendpoints.length - 1; index >= 0; index--) {
    connection.deleteBendpoint(index);    
}
```

**Comment by jbsarrodie** [comment]
I'll provide description of relative coordinates... In a week or two also

**Comment by timhale7** [comment]
Relative Bendpoint Notation
1.	A Relative Bendpoint is notated as a pair of X/Y offsets: {startX, startY, endX, endY}
2.	The startX/startY offset values denote the distance from the starting-object X/Y coordinate to the bendpoint coordinate.
3.	The endX/endY offset values denote the distance from the ending-object X/Y coordinate to the bendpoint coordinate.
4.	Archi calculates the offsets from the centerpoints of the start and end objects.  For example, an object having attributes x=72, y=84, w=120, h=55, has a centerpoint coordinate of (132,111) =  (72 + (120/2), (84 + (55/2).
5.	Using this example:
   a.	Obj1 (start) centerpoint coordinate is 132,111 (x=72, y=84, w=120, h=55)
   b.	Obj2 (end) centerpoint coordinate is 300,195 (x=240, y=168, w=120, h=55)
   c.	Absolute bendpoint coordinate 165,180
   d.	Relative bendpoint offset {startX:33, startY:69, endX:-135, endY:-15}
6.	Calculating absolute bendpoint coordinates, given the relative bendpoint info
   a.	Obj1 coordinate + startX/startY = bendpoint coordinate, thus (132,111) + (33,69) = (165,180)
   b.	Obj2 coordinate + endX/endY = bendpoint coordinate, thus, (300,195) + (-135, -15) = (165,180)
7.	Calcuating relative bendpoint, given the absolute bendpoint coordinate
   a.	bendpoint (X/Y) – start object (X/Y) = (startX/startY), thus, (165,180) – (132,111) = (33,69)
   b.	bendpoint(X/Y) – end object (X/Y) = (endX/endY), thus, (165,180) – (300,195) = (-135,-15)
   c.	relative bendpoint = {startX, startY, endX, endY), thus, {startX:33, startY:69, endX:-135, endY:-15}

**Comment by jbsarrodie** [comment]
> Relative Bendpoint Notation
> 6. Calculating absolute bendpoint coordinates, given the relative bendpoint info
>    a.	Obj1 coordinate + startX/startY = bendpoint coordinate, thus (132,111) + (33,69) = (165,180)
>    b.	Obj2 coordinate + endX/endY = bendpoint coordinate, thus, (300,195) + (-135, -15) = (165,180)

That's not that simple, because (from my memory but I have to double check) what you wrote is true when a bendpoint has just been created, but relative coordinates don't change if you move source and/or target elements. In this case, you have to stretch or shrink values by a factor. This factor is equal to the bounding box of the bendpoint (as described by its relative coordinates) over the bounding box formed by the center of source en target elements.

Not sure that this is clear, I'll try to draw something later to illustrate.

**Comment by timhale7** [comment]
interesting.  I'll try to go check it out this weekend.  i can't find any worthwhile documentation on how relative bendpoints work.  my efforts are a total reverse engineering effort.

**Comment by jbsarrodie** [comment]
>my efforts are a total reverse engineering effort.

So were mine ;-)

**Comment by timhale7** [comment]
not done yet, but have made progress on this.  @jbsarrodie, I can see the pattern you are talking about.

**Comment by timhale7** [comment]
Given:
-	the centerpoint coordinates of two anchor objects: (x+(w/2)), (y+(h/2))
-	a connection between them, having 1 or more bendpoints
-	the midpoint coordinate between the anchor centerpoints
Actions: 
-	move one anchor object to a new position
-	calculate that anchor’s new object-centerpoint
-	calculate the new midpoint coordinate between the revised anchor centerpoints

When a connection has 1 bendpoint: as the anchors move, there is no difference in the relative position of the bendpoint compared to either midpoint.  Said differently, the bendpoints move in a parallel direction and in the same distance as the midpoint moves
When a connection has multiple bendpoints: As the anchors move, the bendpoints move parallel to the  of the midpoints, but not the same distance as the midpoint moves.

I’m still seeking the formula that determines the distance.

**Comment by Phillipus** [comment]
@jbsarrodie wrote a method to convert from relative to absolute bendpoints, it might help:

```java
public static List<Point> getAbsoluteBendpointPositions(IDiagramModelConnection connection) {
        List<Point> points = new ArrayList<Point>();
        
        // TODO: Doesn't work for connection->connection
        if(connection.getSource() instanceof IDiagramModelConnection || connection.getTarget() instanceof IDiagramModelConnection) {
            return points;
        }
        
        double bpindex = 1; // index count + 1
        double bpcount = connection.getBendpoints().size() + 1; // number of bendpoints + 1
        
        for(IDiagramModelBendpoint bendpoint : connection.getBendpoints()) {
            // The weight of this Bendpoint should use to calculate its location.
            // The weight should be between 0.0 and 1.0. A weight of 0.0 will
            // cause the Bendpoint to follow the start point, while a weight
            // of 1.0 will cause the Bendpoint to follow the end point
            double bpweight = bpindex / bpcount;
            
            IBounds srcBounds = getAbsoluteBounds(connection.getSource()); // get bounds of source node
            double startX = (srcBounds.getX() + (srcBounds.getWidth() / 2)) + bendpoint.getStartX();
            startX *= (1.0 - bpweight);
            double startY = (srcBounds.getY() + (srcBounds.getHeight() / 2)) + bendpoint.getStartY();
            startY *= (1.0 - bpweight);
            
            IBounds tgtBounds = getAbsoluteBounds(connection.getTarget()); // get bounds of target node
            double endX = (tgtBounds.getX() + (tgtBounds.getWidth() / 2)) + bendpoint.getEndX();
            endX *= bpweight;
            double endY = (tgtBounds.getY() + (tgtBounds.getHeight() / 2)) + bendpoint.getEndY();
            endY *= bpweight;
            
            int x = (int)(startX + endX);
            int y = (int)(startY + endY);
            
            points.add(new Point(x, y));
            
            bpindex++;
        }
        
        return points;
}
```

**Comment by timhale7** [comment]
I'm pretty sure I've found it.  trivially simple, and not at all what I think it should be doing.
it is just equally distributing the horizontal movement of the ENDPOINTS across the number of bendpoint segments (1 more than the count of bendpoints), and the same for the vertical movement of the ENDPOINT.  No need to calculate anchor centerpoints or the midpoint between them.

so the movement formula is:
BPx-delta-amount = (new-EPx - old-EPx) / (1 + BP-count)
BPy-delta-amount = (new-EPy - old-EPy) / (1 + BP-count)
new-BPx = orig-BPx + Int((BPx-delta-amount * BP-sequence-number))
new BPy = orig-BPy + Int((BPy-delta-amount * BP-sequence-number))

This works equally for a connection with 1 bendpoint, or a connection with multiple bendpoints.  Note: I believe I have the integer truncation positioned correctly.  It works in the several examples I’ve tried.

For example, if the endpoint x movement was 12 and there was 1 bendpoint (thus, 2 bendpoint segments), then BPx-delta-amount = 12/(1+1), or 6.  And the first (only) bendpoint is moved by 6.  Note: this is the same amount of movement of the midpoint of the anchor centerpoints, so it has the illusion of appearing to exactly track the midpoint movement.
If there were 5 bendpoints (thus, 6 bendpoint segments), then BPx-delta-amount = 12/(1+5) or 2.  The first bendpoint is moved by 2, the second bendpoint is moved by 4, the third bendpoint is move by 6, etc.

I was expecting it to preserve some semblance of the aspect ratio by moving the bendpoint proportional to the distance of the bendpoint from the midpoint of the anchor centerpoints.  It is not.

**Comment by timhale7** [comment]
Could we investigate some changes to this behavior?  My typical use case is that I've laid out hand-positioned bendpoints resembling a manhattan layout.  I like visually quiet diagrams, so I usually have multiple bendpoints across multiple connections sharing multiple bendpoints.    When I move 1 anchor object, the default movement moves all of those shared bendpoints, and I have to tediously move them back.

What I'm thinking (but haven't fully vetted) is to have only the last bendpoint in sequence exactly track the movement of the achor object, and keep all of the others frozen in place.  This would preserve the manhattan layout of my other bp's.

**Comment by Phillipus** [comment]
> Could we investigate some changes to this behavior? 

It's been investigated both by me and @jbsarrodie and it wasn't straightforward. I played with fixed bend-points but there was a side effect (which I've forgotten). I'd welcome a solution, but that should be approached outside of this issue.

**Comment by timhale7** [comment]
I think I’ve found an inconsistency in the relative bendpoint coordinates logic after you MOVE source or target objects.  The relative bendpoint coordinates don’t seem to be changing, even though the absolute bendpoint coordinates are.
I made a simple model with 2 objects and a relationship with one bendpoint.
When I export the model to an Open Exchange File, here are the relevant bits: 

- node identifier="id-5e1db267-a107-46cb-a2ff-d52da3490aeb" elementRef="id-5457959c-b81b-4e13-b227-9c366ba57480" xsi:type="Element" x="240" y="384" w="120" h="55     

- node identifier="id-f568ffb8-4189-4b7b-9c31-7eef38168927" elementRef="id-b1963a47-d5b4-4236-976c-999a356ac1ee" xsi:type="Element" x="444" y="516" w="120" h="55"

- bendpoint x="492" y="432"

I wrote a tiny script to reveal the bendpoint coordinates and see this:

- {endY: -111, endX: -12, startY: 21, startX: 192}

When I check the math, these values are consistent:
Souce centerpointX + bendpoint startX = Target centerpointX + bendpoint endX = bendpointX
Source centerpointY + bendpoint startY = Target centerpointY + bendpoint endY = bendpointY

Now, drag the source (or target) object to a new location.  
Unload the model again:

- node identifier="id-5e1db267-a107-46cb-a2ff-d52da3490aeb" elementRef="id-5457959c-b81b-4e13-b227-9c366ba57480" xsi:type="Element" x="144" y="288" w="120" h="55"

- node identifier="id-f568ffb8-4189-4b7b-9c31-7eef38168927" elementRef="id-b1963a47-d5b4-4236-976c-999a356ac1ee" xsi:type="Element" x="444" y="516" w="120" h="55"

- bendpoint x="444" y="384"

Run the script again to reveal the new bendpoint relative coordinates, bit it hasn’t changed.

- {endY: -111, endX: -12, startY: 21, startX: 192}

I can move the source and target objects repeatedly, but this relative bendpoint doesn’t change.
If I touch the bendpoint (that is, move it a tiny bit), the relative coordinates are recalculated correctly.
If there are multiple bendpoints on the connection, moving one of them will recalculate and correct just that one bendpoint’s relative coordinates, but doesn’t touch the others.
